// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIJxi6-Ea7VGBhrUwZCoRBn9EWRgGkVjE',
    appId: '1:202132298198:web:7afd40af05c1e1fb0aac77',
    messagingSenderId: '202132298198',
    projectId: 'loginfirebase-c9b0b',
    authDomain: 'loginfirebase-c9b0b.firebaseapp.com',
    storageBucket: 'loginfirebase-c9b0b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-vK6sMZsrJ343axK3OQ_S3yUe6HqhyO8',
    appId: '1:202132298198:android:df5855eb7eb299e80aac77',
    messagingSenderId: '202132298198',
    projectId: 'loginfirebase-c9b0b',
    storageBucket: 'loginfirebase-c9b0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC__5Fhec2bHhR4KWKCMTLe7RlKVRaV8J0',
    appId: '1:202132298198:ios:4b7ca2ebb1fa91ec0aac77',
    messagingSenderId: '202132298198',
    projectId: 'loginfirebase-c9b0b',
    storageBucket: 'loginfirebase-c9b0b.appspot.com',
    iosClientId:
        '202132298198-vl96hsbtsijtf1phlk0pgt8p522cvduq.apps.googleusercontent.com',
    iosBundleId: 'com.example.gotourApp',
  );
}
