name: modular

sdkPath: .fvm/flutter_sdk

packages:
  - apps/**
  - packages/**

scripts:
  postbootstrap: >
    melos exec -- fvm flutter pub get && 
    fvm dart pub global activate flutter_gen &&
    melos run build_runner

  analyze:
    run: melos exec -- fvm flutter analyze .
    description: Run `dart analyze` in all packages.
    select-package:
      scope:
        - mobile_app
        - gotour_ui

  # Start mobile apps scripts
  run:mobile_app:
    run: melos exec -- fvm flutter run lib/main.dart
    select-package:
      scope:
        - mobile_app

  # run:mobile_app_device_preview:
  #   run: melos exec -- fvm flutter run lib/main_device_preview.dart
  #   select-package:
  #     scope:
  #       - mobile_app

  # # Generation i18n file
  # dev:generate:i18n:
  #   run: melos exec -- "fvm flutter pub run intl_utils:generate"
  #   description: "Generation i18n"
  #   select-package:
  #     flutter: true
  #     scope:
  #       - mobile_app
  #       - gotour_ui

  # # Generation native splash
  # dev:generate:native_splash:
  #   run: melos exec -- fvm flutter pub get && melos exec -- fvm flutter pub run flutter_native_splash:create
  #   description: "Generation asset to display splash screen"
  #   select-package:
  #     scope:
  #       - mobile_app

  # build_runner:
  #   run: |
  #     melos exec -- "fvm flutter pub run build_runner build --delete-conflicting-outputs"
  #   select-package:
  #     scope:
  #       - gotour_ui
  #       - mobile_app

  # # Run widgetbook
  # run:gotour_design:widget_book:
  #   run: melos exec fvm flutter run lib/main.dart
  #   select-package:
  #     scope: gotour_widgetbook
