name: gotour_app
description: GoTour App is a travel and living utility application. we help you discover and buy a variety of tourism products, local services.

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  melos: 3.0.0

flutter:

  uses-material-design: true

